### ISSUE TITLE
WordPress News

### ISSUE THREAD

**Issue by Clorith** [WP-Bot/irc#7]
There's a few ways WordPress.org publishes news, both about upcoming releases, but also when a release is put live, and other interesting news (from https://planet.wordpress.org/ which is an aggregator from approved sources for example).

Should we implement a news notifier for the bot? And if so, should we limit it to only official WordPress.org news, or use the aggregator to get a bit of freshness to it?

**Comment by PeterBooker** [comment]
The aggregrator seems a bit too broad, the current latest article is a review of the `Image SEO` plugin which does not feel appropriate for a broad audience.

The WordPress.org news feels like it would be of interest to most people though. How do you see that working? Something like:

1) Fetch news periodically from the feed `https://wordpress.org/news/feed/`. It seems to suggest it updates hourly, so that seems like a good target for polling frequency.
2) Message/announce any new items (after last GUID- limited to 5 if no GUID stored to cover fresh loads?).
3) Store the latest item by GUID (provided as `<guid isPermaLink="false">https://wordpress.org/news/?p=7425</guid>`

**Comment by Clorith** [comment]
Added in af8942e622fdae47d60ea35d57211df16082dde0 and uses only dotorg news, and not Planet, as it is too broad.
